name: Python CI with pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest test_car.py

      - name: Generate test with pynguin for lift.py and execute it
        run: |
          export PYNGUIN_DANGER_AWARE=x
          pynguin --project-path . --output-path pynguin-action --module-name car -v
          cp car.py pynguin-action/
          pytest pynguin-action/test_car.py
